services:
  tautweekly-manager:
    image: ghcr.io/sev7nrayne/tautweeklywebui:latest

    container_name: TautWeekly-WebUI

    restart: unless-stopped

    environment:
      - TZ=America/New_York

    ports:
      - "8788:8000"

    volumes:
      - /mnt/user/docker/TautWeekly:/tautweekly
      - /mnt/user/docker/TautWeekly/data:/tautweekly/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
