services:
  plexweekly-manager:

    build:
      context: .

    image: plexweekly-manager:latest

    container_name: plexweekly-manager

    restart: unless-stopped

    ports:
      - "8788:8000"

    volumes:
      - /mnt/user/docker/PlexWeekly:/plexweekly:ro
      - /mnt/user/docker/PlexWeekly/data:/plexweekly/data:rw
